angular.module("cvDirectives",[])
.directive("coverInfo",["globalVariables",function(globalVariables){
	return{
		restrict:"E",
		templateUrl:globalVariables.hostname+"include/templates/coverInfo.html"
	}
}])
.directive("personalInfo",["globalVariables",function(globalVariables){
	return{
		restrict:"E",
		templateUrl:globalVariables.hostname+"include/templates/personalInfo.html"
	}
}])
.directive("experienceInfo",["globalVariables",function(globalVariables){
	return{
		restrict:"E",
		templateUrl:globalVariables.hostname+"include/templates/experienceInfo.html"
	}
}])
.directive("knowledgeInfo",["globalVariables",function(globalVariables){
	return{
		restrict:"E",
		templateUrl:globalVariables.hostname+"include/templates/knowledgeInfo.html"
	}
}])
.directive("footerInfo",["globalVariables",function(globalVariables){
	return{
		restrict:"E",
		templateUrl:globalVariables.hostname+"include/templates/footerInfo.html"
	}
}])
